version: "3.9"
networks:
  localnet:
    external: true

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - /prometheus:/etc/prometheus
#    command: prometheus --config.file "/etc/prometheus/prometheus.yml"
    networks:
      localnet:
    ports:
      - "9090:9090"
